- name: configure the master redis server
  hosts: redis-master
  become: yes
  vars:
    - redis_install_dir: /sw/redis
    - redis_dir: /sw/redis
    - redis_conf_dir: /sw/redis/conf
  roles:
    - ../ansible-redis

- name: configure redis slaves
  hosts: redis-slave
  become: yes
  vars:
    - redis_slaveof: 192.168.10.119 6379
    - redis_install_dir: /sw/redis
    - redis_dir: /sw/redis
    - redis_conf_dir: /sw/redis/conf
  roles:
    - ../ansible-redis

- name: configure redis sentinel nodes
  hosts: redis-sentinel
  become: yes
  vars:
    - redis_install_dir: /sw/redis
    - redis_conf_dir: /sw/redis/conf
    - redis_sentinel_dir: /sw/redis/sentinel
    - redis_sentinel_monitors:
      - name: mymaster
        host: 192.168.10.119
        port: 6379
  roles:
    - ../ansible-redis